[package]
org = "ballerina"
name = "data.jsondata"
version = "0.1.0"
authors = ["Ballerina"]
keywords = ["json", "json path", "json-transform", "json transform", "json to json", "json-convert", "json convert"]
repository = "https://github.com/ballerina-platform/module-ballerina-data.jsondata"
license = ["Apache-2.0"]
distribution = "2201.8.4"
export = ["data.jsondata"]

[platform.java17]
graalvmCompatible = true

[[platform.java17.dependency]]
groupId = "io.ballerina.lib"
artifactId = "jsondata-native"
version = "0.1.0"
path = "../native/build/libs/data.jsondata-native-0.1.0-SNAPSHOT.jar"

[[platform.java11.dependency]]
path = "./lib/json-path-2.7.0.jar"
groupId = "com.jayway.jsonpath"
artifactId = "json-path"
version = "2.7.0"
