[plugin]
id = "constraint-compiler-plugin"
class = "io.ballerina.lib.data.jsondata.compiler.JsondataCompilerPlugin"

[[dependency]]
path = "../compiler-plugin/build/libs/data.jsondata-compiler-plugin-0.1.1-SNAPSHOT.jar"
